trigger:
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws_uat'
    regionName: 'eu-west-1'
    imageSource: 'imagename'
    sourceImageName: 'uat'
    repositoryName: '607281769355.dkr.ecr.eu-west-1.amazonaws.com/uat'
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile